version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
  php:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - network_1
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - network_1
volumes:
  postgres-data:
networks:
  network_1:
    driver: bridge