version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "8080:80"
  php:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - network_1
    depends_on:
      - db
  db:
    build:
      context: ./postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network_1
volumes:
  postgres-data:
networks:
  network_1:
    driver: bridge
