version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    network_mode: service:db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
